name: kurye_takip
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6  
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  photo_view: ^0.14.0
  google_nav_bar: ^5.0.6
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.2
  image_picker: ^1.0.7
  get_storage: ^2.1.1
  geocoding: ^2.1.1
  map_picker: ^0.0.3
  flutter_image_compress: ^2.1.0
  intl: ^0.18.1
  #dropdown_button2: ^2.3.9
  dropdown_button2: ^1.4.0
  permission_handler: ^11.1.0
  image_cropper: ^5.0.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  flutter_form_builder: ^9.1.1
  auto_size_text: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  http: ^1.1.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_dark.png"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"
  adaptive_icon_background: "#000000"

flutter:

  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/logo/
    - assets/svgs/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
