// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpLDRhQJOtnUprTJeWdD0nZDg_4lwG28',
    appId: '1:102198727640:web:32138b21dfc62091f798ad',
    messagingSenderId: '102198727640',
    projectId: 'rentekerpushnotification',
    authDomain: 'rentekerpushnotification.firebaseapp.com',
    storageBucket: 'rentekerpushnotification.appspot.com',
    measurementId: 'G-GMRR9FM7P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7d6CMJ6ktffHs8D3Qc8pL5EfZIsFGyQ',
    appId: '1:102198727640:android:0367729bd803c700f798ad',
    messagingSenderId: '102198727640',
    projectId: 'rentekerpushnotification',
    storageBucket: 'rentekerpushnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi5Mhaele_b7Pq-MyBcuBbl0-z2EELfE',
    appId: '1:102198727640:ios:ee7076dbfb4dda65f798ad',
    messagingSenderId: '102198727640',
    projectId: 'rentekerpushnotification',
    storageBucket: 'rentekerpushnotification.appspot.com',
    iosBundleId: 'com.sayazilim.renteker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUi5Mhaele_b7Pq-MyBcuBbl0-z2EELfE',
    appId: '1:102198727640:ios:2a88b6d9df7422b0f798ad',
    messagingSenderId: '102198727640',
    projectId: 'rentekerpushnotification',
    storageBucket: 'rentekerpushnotification.appspot.com',
    iosBundleId: 'com.example.kuryeTakip.RunnerTests',
  );
}
